-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 21:06:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema theater
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `theater` ;

-- -----------------------------------------------------
-- Schema theater
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `theater` DEFAULT CHARACTER SET utf8 ;
USE `theater` ;

-- -----------------------------------------------------
-- Table `theater`.`SeatRow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theater`.`SeatRow` ;

CREATE TABLE IF NOT EXISTS `theater`.`SeatRow` (
  `new_SeatRow` CHAR(2) NOT NULL,
  PRIMARY KEY (`new_SeatRow`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theater`.`SeatNum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theater`.`SeatNum` ;

CREATE TABLE IF NOT EXISTS `theater`.`SeatNum` (
  `new_SeatNum` INT NOT NULL,
  PRIMARY KEY (`new_SeatNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theater`.`Seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theater`.`Seat` ;

CREATE TABLE IF NOT EXISTS `theater`.`Seat` (
  `Section` TEXT(10) NOT NULL,
  `Side` TEXT(6) NOT NULL,
  `PricingTier` TEXT(13) NOT NULL,
  `Wheelchair` TINYINT NOT NULL,
  `SeatRow_new_SeatRow` CHAR(2) NOT NULL,
  `SeatNum_new_SeatNum` INT NOT NULL,
  PRIMARY KEY (`SeatRow_new_SeatRow`, `SeatNum_new_SeatNum`),
  CHECK ((SeatNum_new_SeatNum >= 1 and SeatNum_new_SeatNum <= 15) or (SeatNum_new_SeatNum >= 101 and SeatNum_new_SeatNum <= 126)),
  CHECK (SeatRow_new_SeatRow = 'A' or SeatRow_new_SeatRow = 'B'
  or SeatRow_new_SeatRow = 'C' or SeatRow_new_SeatRow = 'D'
  or SeatRow_new_SeatRow = 'E' or SeatRow_new_SeatRow = 'F'
  or SeatRow_new_SeatRow = 'G' or SeatRow_new_SeatRow = 'H'
  or SeatRow_new_SeatRow = 'J' or SeatRow_new_SeatRow = 'K'
  or SeatRow_new_SeatRow = 'L' or SeatRow_new_SeatRow = 'M'
  or SeatRow_new_SeatRow = 'N' or SeatRow_new_SeatRow = 'O'
    or SeatRow_new_SeatRow = 'P' or SeatRow_new_SeatRow = 'Q'
or SeatRow_new_SeatRow = 'R'
  or SeatRow_new_SeatRow = 'AA' or SeatRow_new_SeatRow = 'BB'
   or SeatRow_new_SeatRow = 'CC' or SeatRow_new_SeatRow = 'DD'
 or SeatRow_new_SeatRow = 'EE' or SeatRow_new_SeatRow = 'FF'
 or SeatRow_new_SeatRow = 'GG' or SeatRow_new_SeatRow = 'HH'),
  
  INDEX `fk_Seat_SeatNum1_idx` (`SeatNum_new_SeatNum` ASC) VISIBLE,
  CONSTRAINT `fk_Seat_SeatRow`
    FOREIGN KEY (`SeatRow_new_SeatRow`)
    REFERENCES `theater`.`SeatRow` (`new_SeatRow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seat_SeatNum`
    FOREIGN KEY (`SeatNum_new_SeatNum`)
    REFERENCES `theater`.`SeatNum` (`new_SeatNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theater`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theater`.`Customer` ;

CREATE TABLE IF NOT EXISTS `theater`.`Customer` (
  `CustomerID` INT NOT NULL,
  `FirstName` TEXT(50) NOT NULL,
  `LastName` TEXT(50) NOT NULL,
  `PaymentMethod` TEXT(15) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theater`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theater`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `theater`.`Ticket` (
  `TicketNumber` INT NOT NULL AUTO_INCREMENT,
  `Showtime` DATETIME NOT NULL,
  `Seat_SeatRow_new_SeatRow` CHAR(2) NOT NULL,
  `Seat_SeatNum_new_SeatNum` INT NOT NULL,
  `Customer_CustomerID` INT NOT NULL,
  PRIMARY KEY (`TicketNumber`),
  INDEX `fk_Ticket_Seat1_idx` (`Seat_SeatRow_new_SeatRow` ASC, `Seat_SeatNum_new_SeatNum` ASC) VISIBLE,
  INDEX `fk_Ticket_Customer1_idx` (`Customer_CustomerID` ASC) VISIBLE,
  CONSTRAINT UNIQUE (Seat_SeatRow_new_SeatRow, Seat_SeatNum_new_SeatNum, Showtime),
  CONSTRAINT `fk_Ticket_Seat1`
    FOREIGN KEY (`Seat_SeatRow_new_SeatRow` , `Seat_SeatNum_new_SeatNum`)
    REFERENCES `theater`.`Seat` (`SeatRow_new_SeatRow` , `SeatNum_new_SeatNum`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ticket_Customer1`
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `theater`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `theater`.`customer` (`CustomerID`, `FirstName`, `LastName`, `PaymentMethod`) VALUES ('1234', 'John', 'Johnson', 'Credit card');

INSERT INTO `theater`.`TICKET` (`Showtime`, `Seat_SeatRow_new_SeatRow`, `Seat_SeatNum_new_SeatNum`, `Customer_CustomerID`) VALUES ('2021/4/15 14:00', 'A', '6', '1234');
INSERT INTO `theater`.`TICKET` (`Showtime`, `Seat_SeatRow_new_SeatRow`, `Seat_SeatNum_new_SeatNum`, `Customer_CustomerID`) VALUES ('2021/4/15 14:00', 'A', '8', '1234');
INSERT INTO `theater`.`TICKET` (`Showtime`, `Seat_SeatRow_new_SeatRow`, `Seat_SeatNum_new_SeatNum`, `Customer_CustomerID`) VALUES ('2021/4/15 14:00', 'A', '10', '1234');
INSERT INTO `theater`.`TICKET` (`Showtime`, `Seat_SeatRow_new_SeatRow`, `Seat_SeatNum_new_SeatNum`, `Customer_CustomerID`) VALUES ('2021/4/15 14:00', 'A', '9', '1234');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
